
const preguntas = [
    { id: 0,
      categoria: "lapices", 
      imagen: "/assets/productos/img1.png",
      nombre: "Lápiz", 
      precio: "1000" 
    },
    { id: 1,
      categoria: "lapices", 
      imagen: "/assets/productos/img2.png",
      nombre: "Resaltador", 
      precio: "3000" 
    },
    { id: 2,
      categoria: "lapices", 
      imagen: "/assets/productos/img3.png",
      nombre: "Crayolas", 
      precio: "6000" 
    },
    { id: 3,
      categoria: "cuadernos", 
      imagen: "/assets/productos/img4.png",
      nombre: "Cuaderno Morado", 
      precio: "10000" 
    },
    { id: 4,
      categoria: "libros", 
      imagen: "/assets/productos/img5.png",
      nombre: "Enciclopedias", 
      precio: "80000" 
    },
    { id: 5,
      categoria: "utiles", 
      imagen: "/assets/productos/img6.png",
      nombre: "Borrador", 
      precio: "1000" 
    },
    { id: 6,
      categoria: "utiles", 
      imagen: "/assets/productos/img7.png",
      nombre: "Grapadora", 
      precio: "15000" 
    },
    { id: 7,
      categoria: "utiles", 
      imagen: "/assets/productos/img8.png",
      nombre: "Pegamento", 
      precio: "12000" 
    },
    { id: 8,
      categoria: "utiles", 
      imagen: "/assets/productos/img9.png",
      nombre: "Tajalapiz", 
      precio: "500" 
    },
    { id: 9,
      categoria: "utiles", 
      imagen: "/assets/productos/img10.png",
      nombre: "Cinta", 
      precio: "5000" 
    },
    { id: 10,
      categoria: "utiles", 
      imagen: "/assets/productos/img11.png",
      nombre: "Portapapeles", 
      precio: "30000" 
    },
    { id: 11,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 12,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 13,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 14,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 15,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 16,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 17,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 18,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 19,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 20,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 21,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 22,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
  
]