
const preguntas = [
    { id: 0,
      categoria: "lapices", 
      imagen: '/papeleria_Productos/img1.png',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 1,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 2,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 3,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 4,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 5,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 6,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 7,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 8,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 9,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 10,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 11,
      categoria: "/papeleria_Productos/img1.png", 
      imagen: 'ruta de la carpeta',
      nombre: "nombre producto", 
      precio: "$precio producto" 
    },
    { id: 12,
      categoria: "lapices", 
      imagen: "assets/productos/img12.png",
      nombre: "ESFERO", 
      precio: "2500" 
    },
    { id: 13,
      categoria: "utiles", 
      imagen: 'assets/productos/img13.png',
      nombre: "TIJERAS", 
      precio: "3000" 
    },
    { id: 14,
      categoria: "utiles", 
      imagen: 'assets/productos/img14.png',
      nombre: "PINTURAS", 
      precio: "10000" 
    },
    { id: 15,
      categoria: "utiles", 
      imagen: 'assets/productos/img15.png',
      nombre: "ACUARELAS", 
      precio: "15000" 
    },
    { id: 16,
      categoria: "utiles", 
      imagen: 'assets/productos/img16.png',
      nombre: "COMBO ESCOLAR", 
      precio: "40000" 
    },
    { id: 17,
      categoria: "libros", 
      imagen: 'assets/productos/img17.png',
      nombre: "ENCICLOPEDIAS", 
      precio: "100000" 
    },
    { id: 18,
      categoria: "utiles", 
      imagen: 'assets/productos/img18.png',
      nombre: "COMPÁS", 
      precio: "20000" 
    },
    { id: 19,
      categoria: "utiles", 
      imagen: 'assets/productos/img19.png',
      nombre: "POSITS", 
      precio: "2000" 
    },
    { id: 20,
      categoria: "cuadernos", 
      imagen: 'assets/productos/img20.png',
      nombre: "LIBRETA ARGOLLADA", 
      precio: "15000" 
    },
    { id: 21,
      categoria: "utiles", 
      imagen: 'assets/productos/img21.png',
      nombre: "MALETA", 
      precio: "100000" 
    },
    { id: 22,
      categoria: "utiles", 
      imagen: 'assets/productos/img22.png',
      nombre: "REGLA", 
      precio: "4000" 
    },
  
]